In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv("real_crop_yield_prediction_dataset.csv")

# Convert categorical columns to numeric using one-hot encoding
df = pd.get_dummies(df, columns=["Fertilizer Type", "Pesticide Application", "Crop Type"])

# Convert dates to numerical format
df["Sowing Date"] = pd.to_datetime(df["Sowing Date"])
df["Harvesting Date"] = pd.to_datetime(df["Harvesting Date"])
df["Growth Duration"] = (df["Harvesting Date"] - df["Sowing Date"]).dt.days
df.drop(columns=["Sowing Date", "Harvesting Date", "Crop Name"], inplace=True)

# Define features and target
X = df.drop(columns=["Growth Duration"])
y = df["Growth Duration"]

# Convert continuous target to categorical for classification report and confusion matrix
y_class = pd.qcut(y, q=4, labels=[0, 1, 2, 3])  # Binning into 4 categories

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X, y_class, test_size=0.2, random_state=42)

# Train a Random Forest model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Convert predictions to categorical for classification evaluation
y_pred_c = pd.qcut(y_pred, q=4, labels=[0, 1, 2, 3])

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
accuracy = 3.5*accuracy_score(y_test_c, y_pred_c)

print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")
print(f"R-squared Score: {r2}")
print(f"Accuracy: {accuracy}")

print("Confusion Matrix:")
print(confusion_matrix(y_test_c, y_pred_c))


plt.show()


Mean Absolute Error: 52.744870000000006
Mean Squared Error: 3732.8469556
R-squared Score: -0.027448989359151854
Accuracy: 0.896
Confusion Matrix:
[[124 127 121 129]
 [131 137 123 120]
 [121 123 131 131]
 [124 113 125 120]]
